### ISSUE TITLE
About the setup of virtual environment and baselines

### ISSUE THREAD

**Issue by Kirito-Ausna** [Immortals-33/Scaffold-Lab#3]
Thank you for your timely work on the protein structure generation benchmark! After reading your paper and codes, I have some confusion and hope you can give me some advice.

- First, the virtual environment for running the evaluation. Maybe the readers can figure out by themselves, I think it's better to provide an official one.
- Then, I would like to know why you created similar codes for 25 targets in RFDiffusion motif-scaffolding benchmark. Are there any special reasons? I understand this repo is under construction, maybe your other unreleased codes in folder Scaffold-Lab will use these similar codes.
- Last, I think for a benchmark work, it's better to train and test all methods in the same framework. Especially these methods use different training sets. I do know how hard it is, but that's the value for a benchmark work. Although, I do appreciate your efforts in such a benchmark, especially in proving various metrics as the baselines didn't provide codes for nolvety, etc.

**Comment by Immortals-33** [comment]
Thank you for your interest in our work! As you've mentioned, this repo is currently went through development which is not set up completely yet, sorry about the delay. Following are my answers:
* We didn't put the environment set-up stage here because some of the evaluation codes are under construction for a complete easy-to-use open source project. Nevertheless, I'll upload a set-up config here for a minimal usage.  
* Are the motif-scaffolding codes for *Chroma* that you referred to? We tested different methods in our work on the benchamrk brought by *RFdiffusion*, whereas these codes are solely for running motif-scaffolding task for *Chroma* using its `SubstructureConditioner` since there is not an official example for running motif-scaffolding task with *Chroma* yet, while the evaluation of other methods referred in our manuscript can be accessed directly on their official page. The reason we put those codes here is for running evaluation on motif-scaffolding with *Chroma* and also for interested users to be used with their customized tasks within this framework. A detailed description on this part is coming soon.
* We did not include this part due to the following reasons:
  * We focused on the strengths and limitations of these methods and wanted to explain the development within this domain, for example, are these proteins robust enough to be combined with downstream tasks and real-world applications? We also expect our framework to be efficient for users to choose the most suitable method under diverse circumstances, which is the reason we made different categories.
  * Training all methods in the same framework is a good idea to compare all the methods on the same level. However, as you've mentioned, this would be a huge computational cost. To my knowledge, some of the model architectures can be trained on a limited scope of protein lengths probably due to RAM, which makes the retraining task more difficult to be realized.  

  Nevertheless, thank you for your suggestion on training and testing all the methods under a framework. Benchmarking on different training sets (for example, like [ProteinInvBench](https://github.com/A4Bio/ProteinInvBench) would be of great help for evaluating the advantages between different architectures, especially for the case in diffusion models that have so many combinations of hyperparameters to be tested.
  
Thanks for your questions! By the way, an updated version of [*Scaffold-Lab*](https://www.biorxiv.org/content/10.1101/2024.02.10.579743v2) is available now. Feel free to read and raise more discussion if you got one.

**Comment by Kirito-Ausna** [comment]
Thank you for your responses! sorry for the late.

It seems that Scaffold-Lab is not a typical benchmark work as e.g., works in NeuIPS datasets and benchmark track. But I think benchmarking from another perspective is also worth efforts:). 

Thank you for your nice work, I will be staying tuned to ScaffLab.
