### ISSUE TITLE
"./demo/motif_scaffolding/motif_info.csv" missing

### ISSUE THREAD

**Issue by blt2114** [Immortals-33/Scaffold-Lab#4]
Hello! Thank you for your nice work.  I'm interested trying out your code but `scaffold_lab/motif_scaffolding/motif_refolding.py` is failing for me, I believe because "./demo/motif_scaffolding/motif_info.csv" is missing.  Could you add in this file?

-Brian

**Comment by Immortals-33** [comment]
Hi Brian,

Thanks for your interest and pointing out this! Seems the file was neglected before. I've uploaded a version corresponds to the demo and a [brief description here](https://github.com/Immortals-33/Scaffold-Lab/tree/main/demo/motif_scaffolding#provide-detailed-information-for-motif-scaffolding-task). Hope this helps! 

Feel free to ask me if you got further questions.

Best,
Zhuoqi

**Comment by blt2114** [comment]
Thanks, Zhuoqi!  It runs for me now.

**Comment by blt2114** [comment]
Hi again, Zhuoqi,

I have another related question.  I am impressed by your great results in your paper reported for GDPL hallucination.

Was that running the open source version on github (https://github.com/sirius777coder/GPDL) with the default settings?

I'm attempting the run that method now to replicate the results.  My main challenge at the moment is that runtime is slow, so I want to be sure I am using the right parameters.

Best,
Brian

**Comment by Immortals-33** [comment]
Hi Brian, 

The results related to motif-scaffolding have been updated recently. In the updated result, we used a combined version of GPDL rather than pure _GPDL-Hallucination_.  Another difference lies on the motif-RMSD in success rate definition. We used **refolded** motif-RMSD to calculate motif-RMSD between the backbone and refolded structures, and lately changed into the calculation between refolded structures and native motifs. The former definition overestimated _RFdiffusion_ and _GPDL-Hallucination_ but it made minimal difference to the performances of _Chroma_ and _TDS_ . Therefore, we switched to the latter definition both in paper and codebase, which is more reasonable and aligns more precisely with those used in previous work. Since we have not updated the preprint yet, we are making a clarification here. You can access the updated results related to this part here:

[Updated Figures.zip](https://github.com/Immortals-33/Scaffold-Lab/files/15171201/Updated.Figures.zip)

In brief, the performances of different methods are different from the previous version, but the main conclusion on motif failure analysis remains unaltered.

Back to your questions about the parameter settings: Yes, the results of _GPDL-Hallucination_ in current version of manuscript used default settings with the optimization step set to 1500. As comparison, the latest version used a integrated version with a pipeline of an initial design by _GPDL-Inpainting_ followed with optimization performed by _GPDL-Hallucination_. The performance of combined version is generally at the same level and improves the model performance to a certain degree. The code of integrated pipeline of _GPDL_  is coming up in the future.

Sorry about the potential confusion. Let me know if you had further questions!

Best, 
Zhuoqi

**Comment by blt2114** [comment]
Hi Zhuoqi,

Thanks for the answer and additional figures. This is helpful and I look forward to the integrated pipeline.

-Brian
